# codeSnips.R

# File to share code samples with the class.
# Do not edit this file, otherwise you will have problems downloading
# updated copies from GitHub.
# ==============================================================================


https://github.com/hyginn/R-EDA

list.files()     # Confirm that the right files are present.
list.files(recursive = TRUE)
list.files(all.files = TRUE)

# ==== reading data things =====================================================
#

Cd19
Cd79b
Cd22
Cd37
Ctsd

myV <- c( "Cd19",
          "Cd79b",
          "Cd22",
          "Cd37",
          "Ctsd")

(x <- "A:B:C")
       strsplit(x, ":")
       strsplit(x, ":")[[1]]
unlist(strsplit(x, ":"))

(x <- c("A:B:C", "D:E"))
       strsplit(x, ":")
       strsplit(x, ":")[[1]]
unlist(strsplit(x, ":"))


-(1:6)
-1:6

# to load an .RData file ...
load("./data/LPSdat.RData")

sort(c(8, 13, 5))
order(c(8, 13, 5))

# ===== column labels ====================================================

a <- c("B", "NK", "Mo", "pDC")
b <- c("ctrl", "LPS")

rep(a, 2)
rep(a, each = 2)

paste(rep(a, each = 2), b)

c("genes", paste(rep(a, each=2), b, sep = "."), "clusters")


# ===== subsetting reloaded ====================================================
# TASK: Write R expressions that get the following data from LPSdat:


#      - rows 1:10 of the first two columns in reverse order

LPSdat[ 10:1 , 1:2 ]

#      - gene names and the expression values for Mo.LPS
#        for the top ten expression values.
#        ( hint: use order() )
x <- LPSdat$Mo.LPS[1:20]
x[order(x, decreasing = TRUE)[1:5]]

ord <- order(LPSdat$Mo.LPS, decreasing = TRUE)[1:10]
LPSdat[ord, c("genes", "Mo.LPS")]

#           Break this down into steps!
#           Which columns?
#           How do we know where the highest values are?


#      - All genes for which B-cells are stimulated by LPS by
#        more than 2 log units.

hist(LPSdat$B.LPS - LPSdat$B.ctrl)

sel <- (LPSdat$B.LPS - LPSdat$B.ctrl) > 2
LPSdat[sel, "genes"]

#      - Expression values for all genes whose gene-names appear in Figure 3B.
#        (hint: use the  %in%  operator)

sel <- LPSdat$genes %in% charGenes
x <- LPSdat[sel, ]

# [end]
