# codeSnips.R

# File to share code samples with the class.
# Do not edit this file, otherwise you will have problems downloading
# updated copies from GitHub.
# ==============================================================================


https://github.com/hyginn/R-EDA

list.files()     # Confirm that the right files are present.
list.files(recursive = TRUE)
list.files(all.files = TRUE)

# ==== reading data things =====================================================
#

Cd19
Cd79b
Cd22
Cd37
Ctsd

myV <- c( "Cd19",
          "Cd79b",
          "Cd22",
          "Cd37",
          "Ctsd")

(x <- "A:B:C")
       strsplit(x, ":")
       strsplit(x, ":")[[1]]
unlist(strsplit(x, ":"))

(x <- c("A:B:C", "D:E"))
       strsplit(x, ":")
       strsplit(x, ":")[[1]]
unlist(strsplit(x, ":"))


-(1:6)
-1:6

# to load an .RData file ...
load("./data/LPSdat.RData")

sort(c(8, 13, 5))
order(c(8, 13, 5))

# ===== column labels ====================================================

a <- c("B", "NK", "Mo", "pDC")
b <- c("ctrl", "LPS")

rep(a, 2)
rep(a, each = 2)

paste(rep(a, each = 2), b)

c("genes", paste(rep(a, each=2), b, sep = "."), "clusters")


# ===== subsetting reloaded ====================================================
# TASK: Write R expressions that get the following data from LPSdat:


#      - rows 1:10 of the first two columns in reverse order

LPSdat[ 10:1 , 1:2 ]

#      - gene names and the expression values for Mo.LPS
#        for the top ten expression values.
#        ( hint: use order() )
x <- LPSdat$Mo.LPS[1:20]
x[order(x, decreasing = TRUE)[1:5]]

ord <- order(LPSdat$Mo.LPS, decreasing = TRUE)[1:10]
LPSdat[ord, c("genes", "Mo.LPS")]

#           Break this down into steps!
#           Which columns?
#           How do we know where the highest values are?


#      - All genes for which B-cells are stimulated by LPS by
#        more than 2 log units.

hist(LPSdat$B.LPS - LPSdat$B.ctrl)

sel <- (LPSdat$B.LPS - LPSdat$B.ctrl) > 2
LPSdat[sel, "genes"]

#      - Expression values for all genes whose gene-names appear in Figure 3B.
#        (hint: use the  %in%  operator)

sel <- LPSdat$genes %in% charGenes
x <- LPSdat[sel, ]

grep("Cd69|Cxcl10|Ifi47|Ifit2", LPSdat$genes)

# ==== boxplot vs. violin ======================================================
#
library(ggplot2)
# install.packages(reshape2)
library(reshape2)

boxplot(gvhdCD3p)

X <- melt(gvhdCD3p)

p <- ggplot(X, aes(x=variable,y=value))
p + geom_violin()

# ===== set.seed() =============================================================

set.seed(3141)
sample(1:5)


# In our LPS data, MF and Mo aught to respond similarly to LPS challenge.
# If so, the LPS - ctrl data should be highly correletd.
#
# TASK:
#  -  is that the case?
#  -  plot the scatterplot for this hypothesis,
#  -  calculate a linear fit
#  -  assess whether there is a linear correlation.
#

# ===== PCA things =============================================================

oPar <- par(mfrow = c(2,1))
plot(x1,y2, xlim=c(-4,4), ylim=c(-4,4))
plot(pcaSample$x[,1],pcaSample$x[,2], xlim=c(-4,4), ylim=c(-4,4))
par(oPar) # restore graphics state parameters

# scale?
plot(crabs[, 5], crabs[, 6], pch=as.numeric(fac))
plot(crabs[, 5], crabs[, 6], xlim = c(0,50), ylim = c(0,50), pch=as.numeric(fac))
plot(scale(crabs[, 5]), scale(crabs[, 6]), pch=as.numeric(fac))


# TASK: Apply PCA to the crabs dataset to distinguish species and sex
#       from morphometric measurements. Plot the results of important
#       PCs as a scatterplot in which blue males are shown as blue
#       triangles, orange males as orange triangles, blue females as
#       blue circles and orange females as orange circles.
#
#       (Advanced: scale the plot symbols with the mean of all
#                  individual measurements)

# scale the data

crabsS <- crabs
crabsS[, 4:8] <- scale(crabs[,4:8])

head(crabs)
head(crabsS)

boxplot(crabs[,4:8])     # original
boxplot(crabsS[,4:8])    # scaled

# run pca
pcaS <- prcomp(crabsS[,4:8])
plot(pcaS)               # the size of the individual PCs

plot(pcaS$x[,2], pcaS$x[,3],   # now "clusters" begin to become apparent
     main = "PCA of scaled data")

# another common way to plot pca-results
biplot(pcaS)
biplot(pcaS, choices = 2:3)

# compare to unscaled values
pcaO <- prcomp(crabs[,4:8])
plot(pcaO$x[,2], pcaO$x[,3],
     main = "PCA of original data")

biplot(pcaO)
biplot(pcaO, choices = 2:3)



# colour- and shape-code the categories

plot(  pcaS$x[,2],         pcaS$x[,3], type ="n")
points(pcaS$x[  1: 50, 2], pcaS$x[  1: 50, 3], pch=17, col="blue")
points(pcaS$x[ 51:100, 2], pcaS$x[ 51:100, 3], pch=19, col="blue")
points(pcaS$x[101:150, 2], pcaS$x[101:150, 3], pch=17, col="orange")
points(pcaS$x[151:200, 2], pcaS$x[151:200, 3], pch=19, col="orange")


plot(  pcaO$x[,2],         pcaO$x[,3], type ="n")
points(pcaO$x[  1: 50, 2], pcaO$x[  1: 50, 3], pch=17, col="blue")
points(pcaO$x[ 51:100, 2], pcaO$x[ 51:100, 3], pch=19, col="blue")
points(pcaO$x[101:150, 2], pcaO$x[101:150, 3], pch=17, col="orange")
points(pcaO$x[151:200, 2], pcaO$x[151:200, 3], pch=19, col="orange")






# using vectors and named vectors to translate values into
# different types of values

myValues <- c("red", "white")
names(myValues) <- c("R", "W")
myValues


# translating index vectors to "map" values:
in1 <- c(1, 2, 1, 1, 2, 1)
myValues[in1]

# translating named vectors by using names
in2 <- c("W", "W", "R", "R", "W", "R")
myValues[in2]

# very(!) useful in many situations - e.g. map values to color, shape, or
# size in a plot; map accession IDs to gene name; ...

myValues <- c("orange", "blue")
names(myValues) <- c("O", "B")

myValues[crabs$sp]
myValues[as.character(crabs$sp)]

x <- character(nrow(crabs))
x[which(crabs$sp == "B")] <- "blue"

crabsPlot(pcaS$x[, 2],
          pcaS$x[, 3],
          crabs$sp,
          crabs$sex,
          rowMeans(crabs[ , 4:8]),
          main  = "Scaled crab categories",
          xlab = "PC 2",
          ylab = "PC 3")

crabsPlot(pcaO$x[, 2],
          pcaO$x[, 3],
          crabs$sp,
          crabs$sex,
          rowMeans(crabs[ , 4:8]),
          main  = "Un-scaled crab categories",
          xlab = "PC 2",
          ylab = "PC 3")

# [end]
