# codeSnips.R

# File to share code samples with the class.
# Do not edit this file, otherwise you will have problems downloading
# updated copies from GitHub.
# ==============================================================================



# [end]
